version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/asset-tag-frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "adarbari"
    assignees:
      - "adarbari"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
  - package-ecosystem: "pip"
    directory: "/asset-tag-backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "adarbari"
    assignees:
      - "adarbari"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "adarbari"
    assignees:
      - "adarbari"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
