/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = &apos;jtzbcspwcqancmrntsud&apos;;
export const publicAnonKey =
  &apos;eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0emJjc3B3Y3FhbmNtcm50c3VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2MTA5NTQsImV4cCI6MjA3NTE4Njk1NH0.TJO1Ts2-ILS24S9B-O9RCmvbKxNIZfN6-q1fjMcpohs&apos;;
