name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd asset-tag-backend
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        
    - name: Run backend tests
      run: |
        cd asset-tag-backend
        python -m pytest tests/ -v --cov=. --cov-report=xml
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: backend-test-results
        path: |
          asset-tag-backend/coverage.xml
          asset-tag-backend/htmlcov/
        retention-days: 30
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: workflow-logs
        path: |
          asset-tag-backend/server.log
        retention-days: 7

  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Install dependencies
      run: |
        cd asset-tag-frontend
        npm install
        
    - name: Run frontend tests
      run: |
        cd asset-tag-frontend
        npm run test:ci
        
    - name: Build frontend
      run: |
        cd asset-tag-frontend
        npm run build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: asset-tag-frontend/build/
        retention-days: 30

  download-artifacts:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download backend test results
      uses: actions/download-artifact@v4
      with:
        name: backend-test-results
        path: ./artifacts/backend/
      continue-on-error: true
      
    - name: Download frontend build
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: ./artifacts/frontend/
      continue-on-error: true
        
    - name: Download workflow logs
      uses: actions/download-artifact@v4
      with:
        name: workflow-logs
        path: ./artifacts/logs/
      continue-on-error: true
        
    - name: List downloaded artifacts
      run: |
        echo "Downloaded artifacts:"
        find ./artifacts -type f -name "*" | head -20
