name: Simple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create test logs
      run: |
        mkdir -p logs
        echo "Test started at $(date)" > logs/test.log
        echo "Running basic validation..." >> logs/test.log
        echo "Test completed at $(date)" >> logs/test.log
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: workflow-logs
        path: logs/
        retention-days: 7
        
  download:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download workflow logs
      uses: actions/download-artifact@v4
      with:
        name: workflow-logs
        path: ./downloaded-logs/
        
    - name: Display logs
      run: |
        echo "Downloaded logs:"
        cat ./downloaded-logs/test.log

  # Auto-fix integration - call the reusable workflow
  auto-fix:
    needs: [test, download]
    if: always() && (needs.test.result == 'failure' || needs.download.result == 'failure')
    uses: ./.github/workflows/auto-fix-reusable.yml
    with:
      workflow-name: "Simple CI"
      workflow-conclusion: "failure"
      logs-content: |
        Test: ${{ needs.test.result }}
        Download: ${{ needs.download.result }}
      error-context: "Simple CI workflow failed - check individual job results"
    permissions:
      contents: write
      issues: write
      pull-requests: write
    secrets: inherit
