name: Test Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: asset-tag-frontend/package-lock.json

    - name: Debug directory structure
      run: |
        echo "Current directory: $(pwd)"
        echo "Contents of current directory:"
        ls -la
        echo "Contents of asset-tag-frontend directory:"
        ls -la asset-tag-frontend/ || echo "asset-tag-frontend directory not found"

    - name: Verify package-lock.json exists
      run: |
        cd asset-tag-frontend
        echo "Current directory: $(pwd)"
        echo "Contents of asset-tag-frontend:"
        ls -la
        if [ ! -f "package-lock.json" ]; then
          echo "❌ package-lock.json not found!"
          echo "Looking for package-lock.json in parent directories..."
          find .. -name "package-lock.json" -type f 2>/dev/null || echo "No package-lock.json found anywhere"
          exit 1
        fi
        echo "✅ package-lock.json found"
        echo "File size: $(wc -c < package-lock.json) bytes"
        echo "Lockfile version: $(node -p "require('./package-lock.json').lockfileVersion")"

    - name: Install dependencies
      run: |
        cd asset-tag-frontend
        npm --version
        echo "Attempting npm ci..."
        if npm ci --verbose; then
          echo "✅ npm ci succeeded"
        else
          echo "❌ npm ci failed, trying npm install as fallback..."
          npm install --verbose
        fi

    - name: Run tests with coverage
      run: |
        cd asset-tag-frontend
        npm run test:coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./asset-tag-frontend/coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Comment coverage on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          try {
            // Read coverage summary
            const coveragePath = path.join(process.cwd(), 'asset-tag-frontend', 'coverage', 'coverage-summary.json');
            if (fs.existsSync(coveragePath)) {
              const coverage = JSON.parse(fs.readFileSync(coveragePath, 'utf8'));
              const summary = coverage.total;
              
              const comment = `## 📊 Test Coverage Report
              
              | Metric | Coverage | Threshold |
              |--------|----------|-----------|
              | **Statements** | ${summary.statements.pct}% | 50% |
              | **Branches** | ${summary.branches.pct}% | 50% |
              | **Functions** | ${summary.functions.pct}% | 50% |
              | **Lines** | ${summary.lines.pct}% | 50% |
              
              ${summary.statements.pct >= 50 && summary.branches.pct >= 50 && summary.functions.pct >= 50 && summary.lines.pct >= 50 ? 
                '✅ All coverage thresholds met!' : 
                '⚠️ Some coverage thresholds not met. Consider adding more tests.'}
              
              <details>
              <summary>Detailed Coverage</summary>
              
              - **Statements**: ${summary.statements.covered}/${summary.statements.total} (${summary.statements.pct}%)
              - **Branches**: ${summary.branches.covered}/${summary.branches.total} (${summary.branches.pct}%)
              - **Functions**: ${summary.functions.covered}/${summary.functions.total} (${summary.functions.pct}%)
              - **Lines**: ${summary.lines.covered}/${summary.lines.total} (${summary.lines.pct}%)
              
              </details>`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }
          } catch (error) {
            console.log('Could not read coverage summary:', error.message);
          }

    - name: Fail if coverage is below threshold
      run: |
        if [ -f "asset-tag-frontend/coverage/coverage-summary.json" ]; then
          node -e "
            const fs = require('fs');
            const coverage = JSON.parse(fs.readFileSync('asset-tag-frontend/coverage/coverage-summary.json', 'utf8'));
            const summary = coverage.total;
            const thresholds = { statements: 50, branches: 50, functions: 50, lines: 50 };
            
            let failed = false;
            for (const [metric, threshold] of Object.entries(thresholds)) {
              if (summary[metric].pct < threshold) {
                console.error(\`❌ \${metric} coverage (\${summary[metric].pct}%) is below threshold (\${threshold}%)\`);
                failed = true;
              } else {
                console.log(\`✅ \${metric} coverage (\${summary[metric].pct}%) meets threshold (\${threshold}%)\`);
              }
            }
            
            if (failed) {
              process.exit(1);
            }
          "
        else
          echo "Coverage summary not found"
          exit 1
        fi

  coverage-badge:
    runs-on: ubuntu-latest
    needs: test-coverage
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: asset-tag-frontend/package-lock.json

    - name: Debug directory structure
      run: |
        echo "Current directory: $(pwd)"
        echo "Contents of current directory:"
        ls -la
        echo "Contents of asset-tag-frontend directory:"
        ls -la asset-tag-frontend/ || echo "asset-tag-frontend directory not found"

    - name: Verify package-lock.json exists
      run: |
        cd asset-tag-frontend
        echo "Current directory: $(pwd)"
        echo "Contents of asset-tag-frontend:"
        ls -la
        if [ ! -f "package-lock.json" ]; then
          echo "❌ package-lock.json not found!"
          echo "Looking for package-lock.json in parent directories..."
          find .. -name "package-lock.json" -type f 2>/dev/null || echo "No package-lock.json found anywhere"
          exit 1
        fi
        echo "✅ package-lock.json found"
        echo "File size: $(wc -c < package-lock.json) bytes"
        echo "Lockfile version: $(node -p "require('./package-lock.json').lockfileVersion")"

    - name: Install dependencies
      run: |
        cd asset-tag-frontend
        npm --version
        echo "Attempting npm ci..."
        if npm ci --verbose; then
          echo "✅ npm ci succeeded"
        else
          echo "❌ npm ci failed, trying npm install as fallback..."
          npm install --verbose
        fi

    - name: Run tests with coverage
      run: |
        cd asset-tag-frontend
        npm run test:coverage

    - name: Generate coverage badge
      run: |
        if [ -f "asset-tag-frontend/coverage/coverage-summary.json" ]; then
          node -e "
            const fs = require('fs');
            const coverage = JSON.parse(fs.readFileSync('asset-tag-frontend/coverage/coverage-summary.json', 'utf8'));
            const summary = coverage.total;
            const overall = Math.round((summary.statements.pct + summary.branches.pct + summary.functions.pct + summary.lines.pct) / 4);
            
            const color = overall >= 80 ? 'brightgreen' : overall >= 60 ? 'yellow' : 'red';
            const badge = \`https://img.shields.io/badge/coverage-\${overall}%25-\${color}\`;
            
            console.log('Coverage badge URL:', badge);
            
            // Update README if it exists
            if (fs.existsSync('README.md')) {
              let readme = fs.readFileSync('README.md', 'utf8');
              const badgeRegex = /!\[Coverage\]\(https:\/\/img\.shields\.io\/badge\/coverage-\d+%25-\w+\)/;
              const newBadge = \`![Coverage](\${badge})\`;
              
              if (badgeRegex.test(readme)) {
                readme = readme.replace(badgeRegex, newBadge);
              } else {
                readme = newBadge + '\n\n' + readme;
              }
              
              fs.writeFileSync('README.md', readme);
              console.log('Updated README with coverage badge');
            }
          "
        fi

    - name: Commit coverage badge
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --staged --quiet || git commit -m "Update coverage badge [skip ci]"
        git push
